### ISSUE TITLE
NFS share is not created when PVC and PV are not created via app/deploymentset.

### ISSUE THREAD

**Issue by ganniterix** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#103]
I have deployed the NFS service and it works when volumes are automatically created with the volumeClaimTemplate. An NFS share is generated and all is fine. However, when I create a PVC and PV, it does not seem to generate the relative NFS share.

**Storage class**
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mynfs-nfs
mountOptions:
- vers=4.1
provisioner: mynfs/nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**PV** (create with and without provisioner_id, no change)

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-storage
    namespace: shares
  nfs:
    path: /export/storage
    server: 10.158.1.1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mynfs-nfs
  volumeMode: Filesystem
```

**PVC**

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage
  namespace: shares
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: mynfs-nfs
  volumeMode: Filesystem
  volumeName: storage
```

I did notice that the EXPORT section is not present when getting the yaml details of the volume, and also vfs.conf is not updated.

*** EDIT ***

The path mentioned above, /export/storage is also not created. It seems the whole folder, and export initialization is skipped.
