### ISSUE TITLE
Extremely poor perfomance with WSL2/Docker Desktop/k8s

### ISSUE THREAD

**Issue by McMac** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#145]
Trying to use nfs-ganesha as local RWM storage on Windows 11 + WSL2 + Docker Desktop + Kubernetes. 

Using this as values.yaml
```yaml
persistence:
  enabled: true
  storageClass: "hostpath"
  size: 100Gi

storageClass:
  defaultClass: true
``` 
and then launching via
`helm install nfs-server-provisioner nfs-ganesha-server-and-external-provisioner/nfs-server-provisioner -f storage/values.yaml`

Testing this with a local Jenkins pipeline, the runtime goes from roughly a minute up to 19 minutes!
![Bild](https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/assets/219912/454f09d8-78ba-473a-8aaa-0e55a13351d9)

Am I doing something wrong? Are the given parameters incomplete? The exact same config works on Mac + Docker Desktop so I am assuming it is related to WSL2/Win somehow. 

Any workarounds? Suggestions? Any updates necessary to nfs ganesha? Parameters? Different default hostpath? Or update to the documentation?
