### ISSUE TITLE
NFS Server not working

### ISSUE THREAD

**Issue by YiannisGkoufas** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#26]
Hi there,

apologies if I am missing out something obvious.
I am using minikube to test out the NFS server and following the instructions and using the deployment:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-provisioner
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-provisioner
  labels:
    app: nfs-provisioner
spec:
  ports:
    - name: nfs
      port: 2049
    - name: nfs-udp
      port: 2049
      protocol: UDP
    - name: nlockmgr
      port: 32803
    - name: nlockmgr-udp
      port: 32803
      protocol: UDP
    - name: mountd
      port: 20048
    - name: mountd-udp
      port: 20048
      protocol: UDP
    - name: rquotad
      port: 875
    - name: rquotad-udp
      port: 875
      protocol: UDP
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
    - name: statd
      port: 662
    - name: statd-udp
      port: 662
      protocol: UDP
  selector:
    app: nfs-provisioner
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      serviceAccountName: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: quay.io/kubernetes_incubator/nfs-provisioner:latest
          ports:
            - name: nfs
              containerPort: 2049
            - name: nfs-udp
              containerPort: 2049
              protocol: UDP
            - name: nlockmgr
              containerPort: 32803
            - name: nlockmgr-udp
              containerPort: 32803
              protocol: UDP
            - name: mountd
              containerPort: 20048
            - name: mountd-udp
              containerPort: 20048
              protocol: UDP
            - name: rquotad
              containerPort: 875
            - name: rquotad-udp
              containerPort: 875
              protocol: UDP
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
            - name: statd
              containerPort: 662
            - name: statd-udp
              containerPort: 662
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
            privileged: true
          args:
            - "-provisioner=example.com/nfs"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: nfs-provisioner
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "Always"
          volumeMounts:
            - name: export-volume
              mountPath: /export
      volumes:
        - name: export-volume
          hostPath:
            path: /tmp/export
```
and rbac:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["nfs-provisioner"]
    verbs: ["use"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner
    # replace with namespace where provisioner is deployed
    namespace: default
roleRef:
  kind: ClusterRole
  name: nfs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner
    # replace with namespace where provisioner is deployed
    namespace: default
roleRef:
  kind: Role
  name: leader-locking-nfs-provisioner
  apiGroup: rbac.authorization.k8s.io
```
In ganesha.log I am getting:
```
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] main :MAIN :EVENT :nfs-ganesha Starting: Ganesha Version 2.8.2
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 90
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] claim_posix_filesystems :FSAL :CRIT :Could not stat directory for path /nonexistent
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] vfs_create_export :FSAL :CRIT :resolve_posix_filesystem(/nonexistent) returned No such file or directory (2)
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] mdcache_fsal_create_export :FSAL :MAJ :Failed to call create_export on underlying FSAL VFS
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] fsal_cfg_commit :CONFIG :CRIT :Could not create export for (/nonexistent) to (/nonexistent)
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] export_commit_common :CONFIG :CRIT :Export id 0 can only export "/" not (/nonexistent)
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] main :NFS STARTUP :WARN :No export entries found in configuration file !!!
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] config_errs_to_log :CONFIG :CRIT :Config File (/export/vfs.conf:28): 1 validation errors in block FSAL
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] config_errs_to_log :CONFIG :CRIT :Config File (/export/vfs.conf:28): Errors processing block (FSAL)
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] config_errs_to_log :CONFIG :CRIT :Config File (/export/vfs.conf:12): 1 validation errors in block EXPORT
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] config_errs_to_log :CONFIG :CRIT :Config File (/export/vfs.conf:12): Errors processing block (EXPORT)
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] nfs_Init_svc :DISP :CRIT :Cannot acquire credentials for principal nfs
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] nfs_Init_admin_thread :NFS CB :EVENT :Admin thread initialized
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] nfs_rpc_cb_init_ccache :NFS STARTUP :EVENT :Callback creds directory (/usr/local/var/run/ganesha) already exists
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] nfs_rpc_cb_init_ccache :NFS STARTUP :WARN :gssd_refresh_krb5_machine_credential failed (-1765328160:22)
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] nfs_Start_threads :THREAD :EVENT :Starting delayed executor.
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] nfs_Start_threads :THREAD :EVENT :gsh_dbusthread was started successfully
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] nfs_Start_threads :THREAD :EVENT :admin thread was started successfully
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] nfs_Start_threads :THREAD :EVENT :reaper thread was started successfully
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] nfs_Start_threads :THREAD :EVENT :General fridge was started successfully
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] nfs_start :NFS STARTUP :EVENT :             NFS SERVER INITIALIZED
04/12/2020 17:46:48 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
04/12/2020 17:48:18 : epoch 5fca7608 : nfs-provisioner-7b87c6b986-j77q9 : nfs-ganesha-22[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE
```

Would appreciate any pointers
