### ISSUE TITLE
Timeout when Pods try to mount volumes referencing PVCs of storageClass `nfs` on K3D cluster

### ISSUE THREAD

**Issue by tricky42** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#34]
**Problem:**
I am trying to get `nfs-server-provisioner` to work in K3D. PVCs and PVs are handled correctly, but Pods cant mount the volume referenced by a PVC. I created an example to make it easy to reproduce the issue in a GitRepo: https://github.com/tricky42/k3d-nfs with a more detailed description. 

In this setup the `local-path` provider from K3D is used to provide the PV for the NFS server automatically through the PVC issued by the `nfs-server-provisioner`. PVCs of storage class `nfs` can be provisioned (status: bound), but still pods trying to mount volumes which reference a PVC of storageClass `nfs`(in this example the PVC `nfs-for-pods`) are not starting up due to: 
```
MountVolume.SetUp failed for volume "pvc-52c0d57a-b285-45b6-b04c-41175604b0d0" : mount failed: exit status 255
Mounting command: mount Mounting arguments: -t nfs -o vers=3 10.43.192.199:/export/pvc-52c0d57a-b285-45b6-b04c-
41175604b0d0 /var/lib/kubelet/pods/c9e21798-76ad-404d-b089-c9fff88e0a86/volumes/kubernetes.io~nfs/pvc-
52c0d57a-b285-45b6-b04c-41175604b0d0 Output: mount: mounting 10.43.192.199:/export/pvc-52c0d57a-b285-45b6-
b04c-41175604b0d0 on /var/lib/kubelet/pods/c9e21798-76ad-404d-b089-c9fff88e0a86/volumes/kubernetes.io~nfs/pvc-
52c0d57a-b285-45b6-b04c-41175604b0d0 failed: Connection refused

Unable to attach or mount volumes: unmounted volumes=[nfs-mount], unattached volumes=[nfs-mount default-token
-t7qxd]: timed out waiting for the condition
```

To quickly reproduce this, just enter:
```
$ make all
```

So far I couldnt find out, why the Pod cant mount the volume managed by the nfs server :(

**Comment by kycfeel** [comment]
I'm having the exact same issue with him. In my case, I'm running a Kubernetes v1.20 (built with kubeadm) on an IBM S390X mainframe. The PV / PVC gets provisioned successfully, but the pod itself just hangs at the container creating status and returns a timed-out error after few mins.

**Comment by kycfeel** [comment]
Ok so for me, I've solved this issue by adding the flags below at the values.yaml (helm chart), `mountOptions`.

```
 mountOptions:
    - tcp
    - nfsvers=4.1
 ```
 
 @tricky42 Can you try with these flags on your environment?

**Comment by tricky42** [comment]
Hi @kycfeel, 

thanks for the tip. Just tried it out and it works. For now I switched to a different solution for our dev setup, but good to know ;) How did you find these config options?

Cheers,

Andreas

**Comment by kvaps** [comment]
@kycfeel @tricky42 could you provide more info on which CNI-plugin and kube-proxy mode is used?

**Comment by kycfeel** [comment]
@kvaps Hey. I'm on a default kube-proxy mode (which is iptables), with the latest flannel CNI.

**Comment by kycfeel** [comment]
@tricky42 I just found it from one of the Stack overflow posts 🤷‍♀️

**Comment by tricky42** [comment]
@kvaps I am using the K3D defaults: iptables and flannel CNI.

@kycfeel Looks like you have better Stackoverflow search skills ;)

**Comment by kycfeel** [comment]
@tricky42 Hey. Can I ask which storage solution are you using for your dev setup?

**Comment by tricky42** [comment]
@kycfeel sure, we are using K3D and the local-path provisioner.
Do you have a link to the stackoverflow post by any chance?

**Comment by h0jeZvgoxFepBQ2C** [comment]
> Ok so for me, I've solved this issue by adding the flags below at the values.yaml (helm chart), `mountOptions`.
> 
> ```
>  mountOptions:
>     - tcp
>     - nfsvers=4.1
> ```
> 
> @tricky42 Can you try with these flags on your environment?

Does this only work for new created volumes? or should I be able to just delete the old nfs-server pod and then the next mounts are using these settings already?

Should this be ok how we are using it? (we use it as a dependency in our own helm chart):

```yaml
# values.yaml
nfs-server-provisioner:
  image:
    repository: gcr.io/k8s-staging-sig-storage/nfs-provisioner
    tag: v3.0.0
  resources:
    requests:
      cpu: 10m
      memory: 190Mi
  persistence:
    enabled: true
    storageClass: "do-block-storage"
    size: 100Gi
  storageClass:
    mountOptions:
      - tcp
      - nfsvers=4.1
```

**Comment by h0jeZvgoxFepBQ2C** [comment]
After updating our cluster from 1.19 to 1.21 we dont get this error anymore.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Just to add further informations to this issue, I guess the root cause was the long (default) timeout for remount tries (which is set to 300 seconds / 5 minutes).

After setting following settings it works pretty fine (this settings only work for newly created PVs, it's doing nothing if you only change it after it has been created!):

```yaml
storageClass:
  ..
  mountOptions:
    - tcp
    - nfsvers=4.1
    - soft
    - retrans=2 # try retransmitting maximum 2 times
    - timeo=10 # timeout after 10 seconds
```
