### ISSUE TITLE
Issues when using more replicas!

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#40]
I'm using the helm chart with the following values:

```
replicaCount: 3

persistence:
  enabled: true

  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: "do-block-storage"

  accessMode: ReadWriteOnce
  size: 10Gi

## For creating the StorageClass automatically:
storageClass:
  create: true

  ## Set a provisioner name. If unset, a name will be generated.
  # provisionerName:

  ## Set StorageClass as the default StorageClass
  ## Ignored if storageClass.create is false
  defaultClass: false

  ## Set a StorageClass name
  ## Ignored if storageClass.create is false
  name: nfs

  # set to null to prevent expansion
  allowVolumeExpansion: true
  ## StorageClass parameters
  parameters: {}

  mountOptions:
    - vers=3

  ## ReclaimPolicy field of the class, which can be either Delete or Retain
  reclaimPolicy: Delete
```

When I try to create `pvc` it stay in the pending state with the following events:

```
Events:
  Type     Reason                Age               From                                                                                                                Message
  ----     ------                ----              ----                                                                                                                -------
  Normal   Provisioning          7s (x2 over 22s)  cluster.local/pro-nfs-nfs-server-provisioner_pro-nfs-nfs-server-provisioner-0_9522a528-c992-48c2-bdc3-6dec4370104d  External provisioner is provisioning volume for claim "default/test-rwx"
  Warning  ProvisioningFailed    7s (x2 over 22s)  cluster.local/pro-nfs-nfs-server-provisioner_pro-nfs-nfs-server-provisioner-0_9522a528-c992-48c2-bdc3-6dec4370104d  failed to provision volume with StorageClass "nfs": error getting NFS server IP for volume: service SERVICE_NAME=pro-nfs-nfs-server-provisioner is not valid; check that it has for ports map[{111 TCP}:true {111 UDP}:true {662 TCP}:true {662 UDP}:true {875 TCP}:true {875 UDP}:true {2049 TCP}:true {2049 UDP}:true {20048 TCP}:true {20048 UDP}:true {32803 TCP}:true {32803 UDP}:true] exactly one endpoint, this pod's IP POD_IP=10.244.1.183
  Normal   ExternalProvisioning  2s (x3 over 22s)  persistentvolume-controller                                                                                         waiting for a volume to be created, either by external provisioner "cluster.local/pro-nfs-nfs-server-provisioner" or manually created by system administrator
```

If I change the `replicaCount` to 1 everything goes fine!
