### ISSUE TITLE
How to use with a specified namespace?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#44]
Right now we are trying to figure out how to install this chart in a dedicated namespace?
But it looks like it's not possible when I look at the chart. Is there any reason for this, so that one can specify one?

Our helmfile looks like following:

```yaml
environments:
  production:
  staging:

repositories:
  - name: kvaps
    url: https://kvaps.github.io/charts

releases:
  - name: {{ .Environment.Name }}
    chart: charts/company
    values:
      - charts/company/configs/{{ .Environment.Name }}.yaml
    set:
      - name: railsmasterkey
        file: config/master.key
  - name: nfs-server-provisioner
    version: 1.2.0
    chart: kvaps/nfs-server-provisioner
    namespace: {{ .Environment.Name }} <--- this is not working?


```

**Comment by kvaps** [comment]
Hi, sorry I'm not much familiar with the helmfile, but I use a few nfs-server-provisioners in dedicated namespace with no problems.

Please make sure that you have different release names for each instance, as each instance generating some cluster-wide resources and rbac rules.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Hm ok, maybe I do something wrong... When I try to set the namespace, it still doesn't get included in the rendered templates as far as I understand it... 

Like following - the namespace is just ignored and not appearing in the rendered template.
At least not when I output this via ```helmfile --debug ... diff```

```yaml
# Source: nfs-server-provisioner/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: company123-nfs-nfs-server-provisioner
  labels:
    app: nfs-server-provisioner
    chart: nfs-server-provisioner-1.2.0
    heritage: Helm
    release: company123-nfs
spec:
...

# Source: nfs-server-provisioner/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: company123-nfs-nfs-server-provisioner
  labels:
    app: nfs-server-provisioner
    chart: nfs-server-provisioner-1.2.0
    heritage: Helm
    release: company123-nfs
spec:
...
```
