### ISSUE TITLE
Use the nfs service DNS name instead of IP to specify the PV

### ISSUE THREAD

**Issue by Gui13** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#79]
Hello,

We've had a disaster recovery on our cluster and we had to re-provision the nfs server provisioner.

When we reprovisioned the server, it created a new service which got a new IP address, which made all the PVs invalid.
We restored the functionality by adding a new ad-hoc service in which we specified the service IP to correspond to the PVs ones. We now need this wart in the cluster.

I was wondering if we could use the nfs service name instead of the IP when provisioning the PVs ?

Right now, when the PV is created, the IP is placed:

```yaml
Source:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    10.222.45.230
    Path:      /export/pvc-fd579ce4-6203-4eb8-a5eb-30436d8cf52f
    ReadOnly:  false
```

See here: https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/blob/09caa21314e7065c89d65589a3d0d19125025894/pkg/volume/provision.go#L451 where we return the service IP instead of the name.

I'm quite sure there's a good reason for doing it via IP, but this is limiting when there's a disaster recoveery. Any idea/comment ?
